logging:
  level: INFO
  path: ./outputs/logs

paths:
  ### Inputs
  patients_info: "azureml://subscriptions/f8c5aac3-29fc-4387-858a-1f61722fb57a/resourcegroups/forskerpl-n0ybkr-rg/workspaces/forskerpl-n0ybkr-mlw/datastores/workspaceblobstore/paths/BREAST_CANCER/formatted_data/med_diag_lab_proc_2024/patients_info.parquet"
  
  initial_pids: "azureml://subscriptions/f8c5aac3-29fc-4387-858a-1f61722fb57a/resourcegroups/forskerpl-n0ybkr-rg/workspaces/forskerpl-n0ybkr-mlw/datastores/researcher_data/paths/corebehrt/data/2024-09-10/old_bc_mdplv/v01/tokenized_new_split/pids_finetune.pt"
  
  ## Exposure, optional, set to outcome if not provided. For multiple exposures, create a joint exposure file.
  # exposure: "researcher-data:elma/data/mammograms_score.csv"

  mammogram_scores: "researcher-data:elma/data/mammograms_score.csv"
  mammogram_raw: "researcher-data:elma/data/mammogram_AndreasLauritzen.csv"
  
  outcome: "researcher-data:elma/base_model/outcomes/breast_cancer.csv" 

  # Model 2.0
  # outcome:  "researcher-data:elma/combined_model/outcomes/breast_cancer.csv" 

  # exclude_pids: # optional, if provided, exclude these pids from the cohort
  
  ### Outputs
  cohort: "researcher-data:elma/base_model/outcomes/breast_cancer_3m"

selection:
  exclude_prior_outcomes: false # Exclude patients who had the outcome before index date
  exposed_only: false # Exclude patients who are not exposed
  age:
    min_years: 0 # Minimum age to include (inclusive)
    max_years: 120 # Maximum age to include (inclusive)
  categories: # here we can include OR exclude categories
    GENDER: # column name in the data
      include: [Kvinde] # include only M/ exclude keyword can be used as well.

index_date: # if not provided we can use exposures to get the index dates
  mode: relative # absolute or relative (to exposure)
  absolute: 
    year: 2015
    month: 1
    day: 26
  relative: # takes first exposure as index date
    n_hours_from_exposure: -2190 # negative means before exposure, 0 by default

cv_folds: 5 # can be set to 1 if only a simple train/val split is needed
test_ratio: 0.1 # can be set to 1 for test set creation only
